# Generated by Django 5.1.4 on 2024-12-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_rename_save_saveitem_save_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='post_videos')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='instagram.post')),
            ],
        ),
    ]
