# Generated by Django 5.1.4 on 2024-12-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_remove_post_video_postvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postvideo',
            old_name='image',
            new_name='video',
        ),
    ]
