# Generated by Django 5.1.4 on 2024-12-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_commentlike_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
    ]
